name: autologin_darwin
description: The platform implementation of the autologin plugin for iOS and MacOS.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_darwin
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      ios:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinDarwin
        sharedDarwinSource: true

dependencies:
  autologin_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  autologin_test_utils:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_test_utils
      ref: 1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
