name: autologin_darwin
description: The iOS and MacOS implementation of the autologin plugin.
version: 0.1.0
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_darwin

environment:
  sdk: ">=3.0.0 <4.0.0"
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      ios:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinDarwin
        sharedDarwinSource: true
      macos:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinDarwin
        sharedDarwinSource: true

dependencies:
  autologin_platform_interface:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_platform_interface
      ref: 0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
