#!/bin/bash
cd ..
echo Dry run of autologin...
flutter pub publish -C autologin --dry-run | grep warnings
echo Dry run of autologin_android...
flutter pub publish -C autologin_android --dry-run | grep warnings
echo Dry run of autologin_darwin...
flutter pub publish -C autologin_darwin --dry-run | grep warnings
echo Dry run of autologin_linux...
flutter pub publish -C autologin_linux --dry-run | grep warnings
echo Dry run of autologin_platform_interface...
flutter pub publish -C autologin_platform_interface --dry-run | grep warnings
echo Dry run of autologin_web...
flutter pub publish -C autologin_web --dry-run | grep warnings
echo Dry run of autologin_windows...
flutter pub publish -C autologin_windows --dry-run | grep warnings
