name: autologin_plugin
description: Library for offering automatic logins with platform methods like smartlock or the keychain.
version: 0.0.3
homepage: https://github.com/rekire/autologin_plugin

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: eu.rekisoft.flutter.autologin
        pluginClass: AutologinPlugin
      ios:
        pluginClass: AutologinPlugin
      web:
        pluginClass: AutologinPlugin
        fileName: autologin_plugin_web.dart
