name: autologin_platform_interface
description: The common platform interface with shared code for the autologin plugin.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_platform_interface

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  very_good_analysis: ">=5.1.0 <7.0.0"
