name: autologin_web
description: The platform implementation of the autologin plugin for web.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_web
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      web:
        pluginClass: AutologinWeb
        fileName: autologin_web.dart

dependencies:
  autologin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ">=5.1.0 <7.0.0"
