name: autologin_web
description: The web implementation of the autologin plugin.
version: 0.0.5
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_web

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  plugin:
    implements: autologin
    platforms:
      web:
        pluginClass: AutologinWeb
        fileName: autologin_web.dart

dependencies:
  autologin_platform_interface:
    path: ../autologin_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
