name: autologin_test_utils
description: Shared code for tests to avoid to duplicating test code.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_test_utils
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  autologin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

# only while development
dependency_overrides:
  autologin_platform_interface:
    path: ../autologin_platform_interface

dev_dependencies:
  very_good_analysis: ^5.1.0
