name: autologin_linux
description: The platform implementation of the autologin plugin for Linux.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_linux
resolution: workspace

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      linux:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinLinux

dependencies:
  autologin_platform_interface: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  autologin_test_utils:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_test_utils
      ref: 1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
