name: autologin_linux
description: Linux implementation of the autologin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      linux:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinLinux

dependencies:
  flutter:
    sdk: flutter
  autologin_platform_interface:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_platform_interface
      ref: 0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
