name: autologin_linux
description: The Platform implementation of the autologin plugin for Linux.
version: 0.1.1
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_linux

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      linux:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinLinux

dependencies:
  autologin_platform_interface: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  autologin_test_utils:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_test_utils
      ref: 0.1.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
