name: autologin_windows
description: The platform implementation of the autologin plugin for Windows.
version: 1.0.0
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_windows

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      windows:
        dartPluginClass: AutologinWindows

dependencies:
  autologin_platform_interface: ^1.0.0
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  autologin_test_utils:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_test_utils
      ref: 1.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
