name: autologin
description: This Plugin helps the developer to auto login into their app as simple as possible.
version: 0.0.6
homepage: https://github.com/rekire/autologin_plugin
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: autologin_android
      ios:
        default_package: autologin_darwin
      #linux:
      #  default_package: autologin_linux
      macos:
        default_package: autologin_darwin
      web:
        default_package: autologin_web
      #windows:
      #  default_package: autologin_windows

dependencies:
  autologin_android:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_android
      ref: 0.0.6
  #autologin_linux:
  #  path: ../autologin_linux
  autologin_darwin:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_darwin
      ref: 0.0.5
  autologin_platform_interface:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_platform_interface
      ref: 0.0.5
  autologin_web:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_web
      ref: 0.0.5
  #autologin_windows:
  #  path: ../autologin_windows
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
