name: autologin
description: This Plugin helps the developer to auto login into their app as simple as possible.
version: 1.0.1
homepage: https://github.com/rekire/autologin_plugin
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: autologin_android
      ios:
        default_package: autologin_darwin
      linux:
        default_package: autologin_linux
      macos:
        default_package: autologin_darwin
      web:
        default_package: autologin_web
      windows:
        default_package: autologin_windows

dependencies:
  autologin_android: ^1.0.1
  autologin_darwin: ^1.0.1
  autologin_linux: ^1.0.1
  autologin_platform_interface: ^1.0.1
  autologin_web: ^1.0.1
  autologin_windows: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ">=5.1.0 <7.0.0"
