name: autologin_android
description: The platform implementation of the autologin plugin for Android.
version: 1.0.0
homepage: https://github.com/rekire/autologin_plugin/tree/main/autologin_android

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      android:
        package: eu.rekisoft.flutter.autologin
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinAndroid

dependencies:
  autologin_platform_interface: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  autologin_test_utils:
    git:
      url: https://github.com/rekire/autologin_plugin.git
      path: autologin_test_utils
      ref: 1.0.0
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
