name: autologin_macos
description: MacOS implementation of the autologin plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: autologin
    platforms:
      macos:
        pluginClass: AutologinPlugin
        dartPluginClass: AutologinMacOS

dependencies:
  flutter:
    sdk: flutter
  autologin_platform_interface:
    path: ../autologin_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
