name: autologin_platform_interface

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_platform_interface.yaml"
      - "autologin_platform_interface/**"
  push:
    paths:
      - ".github/workflows/autologin_platform_interface.yaml"
      - "autologin_platform_interface/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.2
      working_directory: autologin_platform_interface
      format_line_length: 120
