name: autologin_windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_windows.yaml"
      - "autologin_windows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/autologin_windows.yaml"
      - "autologin_windows/**"

jobs:
  build:
    uses: ./.github/workflows/workspace.yaml
    with:
      runs_on: windows-latest
      flutter_channel: stable
      flutter_version: 3.24.1
      analyze_directories: autologin_windows/lib autologin_windows/test
      test_directory: autologin_windows/test
