name: autologin_android

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_android.yaml"
      - "autologin_android/**"
  push:
    paths:
      - ".github/workflows/autologin_android.yaml"
      - "autologin_android/**"

jobs:
  build:
    uses: .github/workflows/workspace.yaml
    with:
      flutter_channel: stable
      flutter_version: 3.24.1
      working_directory: autologin_android
