name: autologin_darwin

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_darwin.yaml"
      - "autologin_darwin/**"
  push:
    paths:
      - ".github/workflows/autologin_darwin.yaml"
      - "autologin_darwin/**"

jobs:
  build:
    uses: ./.github/workflows/workspace.yaml
    with:
      coverage_excludes: '*.g.dart *.freezed.dart'
      flutter_channel: stable
      flutter_version: 3.24.1
      analyze_directories: autologin_android/lib autologin_android/test
      test_directory: autologin_android/test
      working_directory: autologin_darwin
