name: autologin_macos

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_macos.yaml"
      - "autologin_macos/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/autologin_macos.yaml"
      - "autologin_macos/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.13.2
      working_directory: autologin_macos
      format_line_length: 120
