name: autologin_linux

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/autologin_linux.yaml"
      - "autologin_linux/**"
  push:
    paths:
      - ".github/workflows/autologin_linux.yaml"
      - "autologin_linux/**"

jobs:
  build:
    uses: ./.github/workflows/workspace.yaml
    with:
      flutter_channel: stable
      flutter_version: 3.24.1
      analyze_directories: autologin_linux/lib autologin_linux/test
      test_directory: autologin_linux/test
