name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Get libs
        working-directory: autologin
        run: flutter pub get
      - name: Build web
        working-directory: autologin/example
        run: flutter build web
      - name: Upload to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.7.1
        with:
          branch: gh-pages
          folder: autologin/example/build/web
