name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Get libs
        run: flutter pub get
      - name: Analyze lib
        run: flutter analyze
      - name: Test lib
        run: flutter test
      - name: Generate pub report
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
